#nullable enable
using System;
using UnityEngine;
using UnityEngine.Rendering.Universal;

namespace DemonFighter.Presentation.Rendering
{
    /// <summary>
    /// One graphics quality preset (D-083): a name for the settings menu and the URP pipeline asset that carries the
    /// render scale, anti-aliasing, shadow and renderer feature choices. Generated by the render look generator;
    /// the settings menu switches between them.
    /// </summary>
    [Serializable]
    public sealed class GraphicsPreset
    {
        [SerializeField] private string _name = "Medium";
        [SerializeField] private UniversalRenderPipelineAsset _pipeline = null!;

        public string Name => _name;

        /// <summary>The pipeline asset to make current for this preset.</summary>
        public UniversalRenderPipelineAsset Pipeline => _pipeline;

        internal void Configure(string name, UniversalRenderPipelineAsset pipeline)
        {
            _name = name;
            _pipeline = pipeline;
        }
    }
}
