#nullable enable
using System;
using System.Collections.Generic;
using UnityEngine;

namespace DemonFighter.Presentation.Rendering
{
    /// <summary>
    /// The graphics presets the settings menu offers, lowest first, and which one a fresh installation starts with
    /// (D-083). Generated by the render look generator; data only.
    /// </summary>
    [CreateAssetMenu(menuName = "Demon Fighter/Settings/Graphics Presets", fileName = "GraphicsPresets")]
    public sealed class GraphicsPresetCatalog : ScriptableObject
    {
        [SerializeField] private GraphicsPreset[] _presets = Array.Empty<GraphicsPreset>();
        [SerializeField] private int _defaultIndex;

        /// <summary>The presets, lowest quality first.</summary>
        public IReadOnlyList<GraphicsPreset> Presets => _presets;

        /// <summary>Index of the preset a fresh installation uses.</summary>
        public int DefaultIndex => Mathf.Clamp(_defaultIndex, 0, Mathf.Max(0, _presets.Length - 1));

        /// <summary>The preset with this name, or the default when the name is unknown.</summary>
        public GraphicsPreset Find(string? name)
        {
            for (int i = 0; i < _presets.Length; i++)
            {
                if (string.Equals(_presets[i].Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    return _presets[i];
                }
            }

            if (_presets.Length == 0)
            {
                throw new InvalidOperationException("The graphics preset catalog is empty; run Demon Fighter > Generate > Placeholder Assets.");
            }

            return _presets[DefaultIndex];
        }

        internal void Configure(GraphicsPreset[] presets, int defaultIndex)
        {
            _presets = presets ?? throw new ArgumentNullException(nameof(presets));
            _defaultIndex = defaultIndex;
        }
    }
}
