#nullable enable
using DemonFighter.Simulation;
using UnityEngine;

namespace DemonFighter.Presentation
{
    /// <summary>
    /// The materials of the primitive stage (ASSET_PIPELINE, "Placeholder standard"): one per world feature, one per
    /// demon role or tier, and the gore set (blood decals, viscera). Generated by Demon Fighter > Generate >
    /// Placeholder Assets; views only read it.
    /// </summary>
    [CreateAssetMenu(menuName = "Demon Fighter/Settings/Placeholder Palette", fileName = "PlaceholderPalette")]
    public sealed class PlaceholderPalette : ScriptableObject
    {
        [SerializeField] private Material _ground = null!;
        [SerializeField] private Material _wall = null!;
        [SerializeField] private Material _rock = null!;
        [SerializeField] private Material _fissure = null!;
        [SerializeField] private Material _lava = null!;
        [SerializeField] private Material _water = null!;
        [SerializeField] private Material _bone = null!;
        [SerializeField] private Material _player = null!;
        [SerializeField] private Material[] _demonTiers = System.Array.Empty<Material>();
        [SerializeField] private Material _elder = null!;
        [SerializeField] private Material _corpse = null!;
        [SerializeField] private Material _blood = null!;
        [SerializeField] private Material _maw = null!;
        [SerializeField] private Material _eye = null!;
        [SerializeField] private Material _plate = null!;
        [SerializeField] private Material[] _bloodSplats = System.Array.Empty<Material>();
        [SerializeField] private Material _bloodPool = null!;
        [SerializeField] private Material _viscera = null!;
        [SerializeField] private Material _embers = null!;
        [SerializeField, HideInInspector] private int _generatorVersion;

        public Material Ground => _ground;

        public Material Wall => _wall;

        public Material Rock => _rock;

        public Material Fissure => _fissure;

        public Material Lava => _lava;

        public Material Water => _water;

        public Material Bone => _bone;

        /// <summary>Dead flesh: corpses and severed parts.</summary>
        public Material Corpse => _corpse;

        /// <summary>Flat blood for anything that is not a decal.</summary>
        public Material Blood => _blood;

        /// <summary>The snout that marks the front of every placeholder demon.</summary>
        public Material Maw => _maw;

        /// <summary>Eyes on a placeholder body.</summary>
        public Material Eye => _eye;

        /// <summary>Plates and spines: dark, hard, a little metallic.</summary>
        public Material Plate => _plate;

        /// <summary>Decal materials of the blood splats on the ground, one per splat texture (D-081).</summary>
        public Material[] BloodSplats => _bloodSplats;

        /// <summary>Decal material of the pool that spreads under a corpse.</summary>
        public Material BloodPool => _bloodPool;

        /// <summary>Wet flesh of the viscera pieces.</summary>
        public Material Viscera => _viscera;

        /// <summary>Additive glowing particles for sparks off burning bodies and embers over lava (D-086).</summary>
        public Material Embers => _embers;

        /// <summary>Picks the material for a demon: teal for the player, by tier for AI, near black for elders.</summary>
        public Material ForDemon(Demon demon)
        {
            if (demon.Controller == ControllerKind.Player)
            {
                return _player;
            }

            if (demon.Tier >= _demonTiers.Length)
            {
                return _elder;
            }

            return _demonTiers[demon.Tier];
        }

        /// <summary>The version of the placeholder generator that last wrote the generated assets; the editor reruns it when older.</summary>
        internal int GeneratorVersion => _generatorVersion;

        internal void StampGenerator(int version)
        {
            _generatorVersion = version;
        }

        internal void SetMaterials(
            Material ground,
            Material wall,
            Material rock,
            Material fissure,
            Material lava,
            Material water,
            Material bone,
            Material player,
            Material[] demonTiers,
            Material elder,
            Material corpse,
            Material blood,
            Material maw,
            Material eye,
            Material plate)
        {
            _ground = ground;
            _wall = wall;
            _rock = rock;
            _fissure = fissure;
            _lava = lava;
            _water = water;
            _bone = bone;
            _player = player;
            _demonTiers = demonTiers;
            _elder = elder;
            _corpse = corpse;
            _blood = blood;
            _maw = maw;
            _eye = eye;
            _plate = plate;
        }

        internal void SetGore(Material[] bloodSplats, Material bloodPool, Material viscera, Material embers)
        {
            _bloodSplats = bloodSplats;
            _bloodPool = bloodPool;
            _viscera = viscera;
            _embers = embers;
        }
    }
}
