#nullable enable
using System;
using System.IO;
using UnityEngine;

namespace DemonFighter.Editor.Generate
{
    /// <summary>
    /// Synthesizes the placeholder sounds (D-084) from sines, noise and envelopes, deterministic per seed, so the
    /// whole audio path is audible before any recorded or generated clip exists. Loops are built from tones with
    /// whole cycles over their length and a crossfaded seam, so they repeat without a click. Music placeholders are
    /// temporary by design: the real music is AI-generated by Mario (D-030). Mono 16-bit WAV at 22050 Hz.
    /// </summary>
    internal static class AudioSynth
    {
        public const int SampleRate = 22050;

        private const float Peak = 0.9f;
        private const float LoopFadeSeconds = 0.25f;

        public static float[] Bite(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.35f);
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float snap = Noise(random) * Decay(t, 0.02f);
                float thump = Mathf.Sin(Phase(90f - 40f * t, t)) * Decay(t, 0.09f);
                float crunch = t > 0.08f ? Noise(random) * Decay(t - 0.08f, 0.05f) * 0.6f : 0f;
                samples[i] = snap * 0.6f + thump * 0.9f + crunch;
            }

            return Finish(samples, 0.08f);
        }

        public static float[] Claw(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.3f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float envelope = Mathf.Sin(Mathf.Clamp01(t / 0.3f) * Mathf.PI);
                filtered += (Noise(random) - filtered) * (0.15f + 0.5f * (1f - t / 0.3f));
                float scrape = t > 0.12f ? Noise(random) * Decay(t - 0.12f, 0.04f) * 0.5f : 0f;
                samples[i] = filtered * envelope + scrape;
            }

            return Finish(samples, 0.15f);
        }

        public static float[] Grab(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.4f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                filtered += (Noise(random) - filtered) * 0.2f;
                float squelch = filtered * (0.5f + 0.5f * Mathf.Sin(Phase(28f, t))) * Decay(t, 0.18f);
                float thud = Mathf.Sin(Phase(75f, t)) * Decay(t, 0.08f);
                samples[i] = squelch * 0.8f + thud * 0.7f;
            }

            return Finish(samples, 0.03f);
        }

        public static float[] Lunge(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.5f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float envelope = Mathf.Sin(Mathf.Clamp01(t / 0.5f) * Mathf.PI);
                filtered += (Noise(random) - filtered) * (0.08f + 0.3f * t);
                samples[i] = filtered * envelope * 1.2f;
            }

            return Finish(samples, 0.2f);
        }

        public static float[] TailSwing(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.45f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float envelope = Mathf.Sin(Mathf.Clamp01(t / 0.35f) * Mathf.PI);
                filtered += (Noise(random) - filtered) * 0.06f;
                float crack = t > 0.3f ? Noise(random) * Decay(t - 0.3f, 0.015f) : 0f;
                samples[i] = filtered * envelope * 1.5f + crack * 0.8f;
            }

            return Finish(samples, 0.15f);
        }

        public static float[] WetImpact(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.3f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float thud = Mathf.Sin(Phase(70f - 30f * t, t)) * Decay(t, 0.1f);
                filtered += (Noise(random) - filtered) * 0.35f;
                float splat = filtered * Decay(t, 0.07f);
                samples[i] = thud * 0.9f + splat * 0.7f;
            }

            return Finish(samples, 0.02f);
        }

        public static float[] Footstep(int seed)
        {
            var random = new System.Random(seed);
            float frequency = 60f + (float)random.NextDouble() * 50f;
            float[] samples = Silence(0.15f);
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float thud = Mathf.Sin(Phase(frequency, t)) * Decay(t, 0.04f);
                float tap = Noise(random) * Decay(t, 0.008f);
                samples[i] = thud * 0.9f + tap * 0.4f;
            }

            return Finish(samples, 0.03f);
        }

        public static float[] Eat(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.5f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                filtered += (Noise(random) - filtered) * 0.25f;
                float bursts = Mathf.Max(0f, Mathf.Sin(Phase(6f, t)));
                samples[i] = filtered * bursts * bursts * Decay(t, 0.4f);
            }

            return Finish(samples, 0.08f);
        }

        public static float[] MutationStart(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(1.2f);
            float phase = 0f;
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float frequency = 110f + 220f * (t / 1.2f) + 6f * Mathf.Sin(Phase(5f, t));
                phase += frequency / SampleRate * Mathf.PI * 2f;
                float tone = Mathf.Sin(phase) * Mathf.Sin(Mathf.Clamp01(t / 1.2f) * Mathf.PI);
                filtered += (Noise(random) - filtered) * 0.05f;
                samples[i] = tone * 0.8f + filtered * 0.8f * (t / 1.2f);
            }

            return Finish(samples, 0.1f);
        }

        public static float[] MutationComplete(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.8f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                filtered += (Noise(random) - filtered) * 0.3f;
                float pop = filtered * Decay(t, 0.05f);
                float chord = (Mathf.Sin(Phase(220f, t)) + Mathf.Sin(Phase(330f, t)) * 0.7f) * Decay(t, 0.3f) * Mathf.Clamp01(t / 0.03f);
                samples[i] = pop * 0.8f + chord * 0.5f;
            }

            return Finish(samples, 0.1f);
        }

        public static float[] Evolved(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(1.6f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float swell = Mathf.Sin(Mathf.Clamp01(t / 1.6f) * Mathf.PI);
                float chord = Mathf.Sin(Phase(110f, t)) + Mathf.Sin(Phase(165f, t)) * 0.8f + Mathf.Sin(Phase(220f, t)) * 0.6f;
                filtered += (Noise(random) - filtered) * 0.04f;
                samples[i] = chord * swell * 0.4f + filtered * swell * 1.2f;
            }

            return Finish(samples, 0.2f);
        }

        public static float[] LevelUp(int seed)
        {
            float[] samples = Silence(0.6f);
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float first = Mathf.Sin(Phase(660f, t)) * Decay(t, 0.15f);
                float second = t > 0.15f ? Mathf.Sin(Phase(880f, t - 0.15f)) * Decay(t - 0.15f, 0.25f) : 0f;
                samples[i] = first * 0.6f + second * 0.7f;
            }

            return Finish(samples, 0.1f);
        }

        public static float[] ThreatRise(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(1.2f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float drone = (Mathf.Sin(Phase(55f, t)) + Mathf.Sin(Phase(82.5f, t)) * 0.6f) * Decay(t, 0.5f);
                filtered += (Noise(random) - filtered) * 0.03f;
                samples[i] = drone * 0.9f + filtered * Decay(t, 0.3f) * 1.5f;
            }

            return Finish(samples, 0.2f);
        }

        public static float[] PlayerDeath(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(2.5f);
            float phase = 0f;
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float frequency = Mathf.Lerp(220f, 40f, Mathf.Clamp01(t / 2.5f));
                phase += frequency / SampleRate * Mathf.PI * 2f;
                filtered += (Noise(random) - filtered) * 0.08f;
                samples[i] = Mathf.Sin(phase) * Decay(t, 1.2f) * 0.7f + filtered * Decay(t, 0.9f) * 1.4f;
            }

            return Finish(samples, 0.4f);
        }

        public static float[] DemonDeath(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(1f);
            float phase = 0f;
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float frequency = Mathf.Lerp(180f, 60f, Mathf.Clamp01(t));
                phase += frequency / SampleRate * Mathf.PI * 2f;
                filtered += (Noise(random) - filtered) * 0.2f;
                float gurgle = filtered * (0.5f + 0.5f * Mathf.Sin(Phase(18f, t))) * Decay(t, 0.45f);
                samples[i] = Mathf.Sin(phase) * Decay(t, 0.4f) * 0.6f + gurgle;
            }

            return Finish(samples, 0.2f);
        }

        public static float[] Sever(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.5f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float crack = Noise(random) * Decay(t, 0.01f);
                filtered += (Noise(random) - filtered) * 0.3f;
                float tear = t > 0.03f ? filtered * (0.6f + 0.4f * Mathf.Sin(Phase(22f, t))) * Decay(t - 0.03f, 0.2f) : 0f;
                samples[i] = crack + tear * 0.9f;
            }

            return Finish(samples, 0.08f);
        }

        /// <summary>Flesh hitting lava: a hiss with crackles and a low simmer under it.</summary>
        public static float[] Burn(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.7f);
            float hiss = 0f;
            float simmer = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float white = Noise(random);
                hiss = white - hiss * 0.6f;
                simmer += (Noise(random) - simmer) * 0.02f;
                float crackle = random.NextDouble() < 0.004 ? Noise(random) * 2f : 0f;
                float envelope = Mathf.Clamp01(t / 0.03f) * Decay(t, 0.35f);
                samples[i] = (hiss * 0.35f + crackle) * envelope + simmer * 2.5f * Decay(t, 0.5f);
            }

            return Finish(samples, 0.15f);
        }

        public static float[] PartDestroyed(int seed)
        {
            var random = new System.Random(seed);
            float[] samples = Silence(0.4f);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                filtered += (Noise(random) - filtered) * 0.5f;
                float bursts = Mathf.Max(0f, Mathf.Sin(Phase(14f, t)));
                samples[i] = filtered * (0.4f + 0.6f * bursts) * Decay(t, 0.2f);
            }

            return Finish(samples, 0.05f);
        }

        /// <summary>The cavern drone: a sub tone and its fifth under slow filtered noise; seamless over the given length.</summary>
        public static float[] CavernDrone(float seconds, int seed)
        {
            var random = new System.Random(seed);
            float[] samples = LoopSilence(seconds);
            float low = LoopFrequency(55f, seconds);
            float fifth = LoopFrequency(82.5f, seconds);
            float lfo = LoopFrequency(0.125f, seconds);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                filtered += (Noise(random) - filtered) * 0.02f;
                float breath = 0.6f + 0.4f * Mathf.Sin(Phase(lfo, t));
                samples[i] = Mathf.Sin(Phase(low, t)) * 0.5f + Mathf.Sin(Phase(fifth, t)) * 0.2f + filtered * 2f * breath;
            }

            return FinishLoop(samples);
        }

        /// <summary>Lava: a low rumble with pops and bubbles; seamless over the given length.</summary>
        public static float[] LavaLoop(float seconds, int seed)
        {
            var random = new System.Random(seed);
            float[] samples = LoopSilence(seconds);
            float rumble = 0f;
            float bubble = 0f;
            float popLeft = 0f;
            float popPhase = 0f;
            float popFrequency = 200f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                rumble += (Noise(random) - rumble) * 0.01f;
                bubble += (Noise(random) - bubble) * 0.3f;
                float bubbling = bubble * Mathf.Max(0f, Mathf.Sin(Phase(1.5f, t)) - 0.3f) * 0.6f;
                if (popLeft <= 0f && random.NextDouble() < 0.0004)
                {
                    popLeft = 0.12f;
                    popFrequency = 150f + (float)random.NextDouble() * 250f;
                    popPhase = 0f;
                }

                float pop = 0f;
                if (popLeft > 0f)
                {
                    popPhase += popFrequency / SampleRate * Mathf.PI * 2f;
                    pop = Mathf.Sin(popPhase) * Decay(0.12f - popLeft, 0.03f) * 0.5f;
                    popLeft -= 1f / SampleRate;
                }

                samples[i] = rumble * 3f + bubbling + pop;
            }

            return FinishLoop(samples);
        }

        /// <summary>Menu placeholder: a slow pad that moves between two chords; seamless over the given length.</summary>
        public static float[] MenuTrack(float seconds)
        {
            float[] samples = LoopSilence(seconds);
            float a = LoopFrequency(110f, seconds);
            float e = LoopFrequency(165f, seconds);
            float f = LoopFrequency(87.3f, seconds);
            float c = LoopFrequency(130.8f, seconds);
            float change = LoopFrequency(1f / seconds, seconds);
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float blend = 0.5f + 0.5f * Mathf.Sin(Phase(change, t));
                float first = Mathf.Sin(Phase(a, t)) + Mathf.Sin(Phase(e, t)) * 0.7f;
                float second = Mathf.Sin(Phase(f, t)) + Mathf.Sin(Phase(c, t)) * 0.7f;
                samples[i] = Mathf.Lerp(first, second, blend) * 0.5f;
            }

            return FinishLoop(samples);
        }

        /// <summary>Calm placeholder: a breathing pad with a soft noise bed; seamless over the given length.</summary>
        public static float[] CalmTrack(float seconds, int seed)
        {
            var random = new System.Random(seed);
            float[] samples = LoopSilence(seconds);
            float a = LoopFrequency(110f, seconds);
            float e = LoopFrequency(165f, seconds);
            float lfo = LoopFrequency(0.125f, seconds);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float breath = 0.7f + 0.3f * Mathf.Sin(Phase(lfo, t));
                filtered += (Noise(random) - filtered) * 0.015f;
                samples[i] = (Mathf.Sin(Phase(a, t)) + Mathf.Sin(Phase(e, t)) * 0.6f) * breath * 0.4f + filtered * 1.2f;
            }

            return FinishLoop(samples);
        }

        /// <summary>Combat placeholder: the pad with a pulse every half second and a tremolo; seamless over the given length.</summary>
        public static float[] CombatTrack(float seconds, int seed)
        {
            var random = new System.Random(seed);
            float[] samples = LoopSilence(seconds);
            float a = LoopFrequency(110f, seconds);
            float e = LoopFrequency(165f, seconds);
            float tremolo = LoopFrequency(4f, seconds);
            float filtered = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                float t = Time(i);
                float beat = t - Mathf.Floor(t * 2f) * 0.5f;
                float tom = Mathf.Sin(Phase(70f - 40f * beat, beat)) * Decay(beat, 0.08f);
                filtered += (Noise(random) - filtered) * 0.4f;
                float click = filtered * Decay(beat, 0.01f);
                float pad = (Mathf.Sin(Phase(a, t)) + Mathf.Sin(Phase(e, t)) * 0.6f) * (0.6f + 0.4f * Mathf.Sin(Phase(tremolo, t)));
                samples[i] = pad * 0.35f + tom * 0.9f + click * 0.4f;
            }

            return FinishLoop(samples);
        }

        /// <summary>A mono 16-bit PCM WAV file of the samples.</summary>
        public static byte[] ToWav(float[] samples, int sampleRate)
        {
            if (samples == null)
            {
                throw new ArgumentNullException(nameof(samples));
            }

            using var stream = new MemoryStream(44 + samples.Length * 2);
            using var writer = new BinaryWriter(stream);
            writer.Write(new[] { 'R', 'I', 'F', 'F' });
            writer.Write(36 + samples.Length * 2);
            writer.Write(new[] { 'W', 'A', 'V', 'E' });
            writer.Write(new[] { 'f', 'm', 't', ' ' });
            writer.Write(16);
            writer.Write((short)1);
            writer.Write((short)1);
            writer.Write(sampleRate);
            writer.Write(sampleRate * 2);
            writer.Write((short)2);
            writer.Write((short)16);
            writer.Write(new[] { 'd', 'a', 't', 'a' });
            writer.Write(samples.Length * 2);
            for (int i = 0; i < samples.Length; i++)
            {
                writer.Write((short)Mathf.RoundToInt(Mathf.Clamp(samples[i], -1f, 1f) * short.MaxValue));
            }

            writer.Flush();
            return stream.ToArray();
        }

        /// <summary>
        /// Closes a loop that was synthesized a fade longer than it plays: the overhang past the loop length is blended
        /// into the head and cut off, so the last sample runs straight into the first and the seam has no click.
        /// </summary>
        public static float[] CrossfadeLoop(float[] samplesWithOverhang, int fadeSamples)
        {
            if (samplesWithOverhang == null)
            {
                throw new ArgumentNullException(nameof(samplesWithOverhang));
            }

            int fade = Mathf.Clamp(fadeSamples, 0, samplesWithOverhang.Length / 2);
            int length = samplesWithOverhang.Length - fade;
            var loop = new float[length];
            Array.Copy(samplesWithOverhang, loop, length);
            for (int i = 0; i < fade; i++)
            {
                float blend = (i + 1) / (float)(fade + 1);
                loop[i] = Mathf.Lerp(samplesWithOverhang[length + i], samplesWithOverhang[i], blend);
            }

            return loop;
        }

        /// <summary>The nearest frequency with a whole number of cycles over the loop, so the loop closes.</summary>
        public static float LoopFrequency(float frequency, float seconds)
        {
            return Mathf.Max(1f, Mathf.Round(frequency * seconds)) / seconds;
        }

        private static float[] Finish(float[] samples, float tailSeconds)
        {
            FadeOut(samples, tailSeconds);
            return Normalize(samples);
        }

        private static float[] FinishLoop(float[] samples)
        {
            Normalize(samples);
            return CrossfadeLoop(samples, Mathf.RoundToInt(LoopFadeSeconds * SampleRate));
        }

        private static float[] Silence(float seconds)
        {
            return new float[Mathf.Max(1, Mathf.RoundToInt(seconds * SampleRate))];
        }

        // A loop is synthesized one fade longer than it plays; CrossfadeLoop blends the overhang away.
        private static float[] LoopSilence(float seconds)
        {
            return Silence(seconds + LoopFadeSeconds);
        }

        private static float Time(int sample)
        {
            return sample / (float)SampleRate;
        }

        private static float Phase(float frequency, float t)
        {
            return frequency * t * Mathf.PI * 2f;
        }

        private static float Decay(float t, float tau)
        {
            return t < 0f ? 0f : Mathf.Exp(-t / tau);
        }

        private static float Noise(System.Random random)
        {
            return (float)random.NextDouble() * 2f - 1f;
        }

        private static void FadeOut(float[] samples, float seconds)
        {
            int fade = Mathf.Clamp(Mathf.RoundToInt(seconds * SampleRate), 1, samples.Length);
            for (int i = 0; i < fade; i++)
            {
                int index = samples.Length - fade + i;
                samples[index] *= 1f - (i + 1) / (float)fade;
            }
        }

        private static float[] Normalize(float[] samples)
        {
            float peak = 0f;
            for (int i = 0; i < samples.Length; i++)
            {
                peak = Mathf.Max(peak, Mathf.Abs(samples[i]));
            }

            if (peak > 0f)
            {
                float gain = Peak / peak;
                for (int i = 0; i < samples.Length; i++)
                {
                    samples[i] *= gain;
                }
            }

            return samples;
        }
    }
}
